# Generated by Django 4.2.3 on 2023-12-17 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0004_alter_userprofile_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='is_online',
            field=models.BooleanField(default='None'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='picture',
            field=models.CharField(default='None', max_length=1000),
        ),
    ]
