# Generated by Django 4.2.3 on 2023-12-17 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0006_alter_userprofile_is_online'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='picture',
            field=models.JSONField(default=dict),
        ),
    ]
